language: python

python:
    - "2.7"
    - "3.3"

install:
    - pip install pytest-cov
    - pip install pytest-pep8
    - pip install coveralls

script: py.test test_schedule.py --pep8 schedule -v --cov schedule --cov-report term-missing

after_success:
    - coveralls
